name: Continuous Delivery
on:
  push:
    branches:
      - main # qualquer outra coisa

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/checkout@v4
        with:
          name: projetozipado.zip
          path: |
            '**.py'
            README.md